// Deterministic build for com.ikenga.tasks — P3 increment 2 (anti-drift).
//
// The two CSS-as-JS-string artifacts under dist/lib/ used to be hand-maintained
// (P3 inc-1 swapped tokens-css.js to the reconciled @ikenga/tokens but left it a
// hand-copied vendor; tasks-css.js was a hand-escaped mirror of tasks.css). This
// script makes both deterministically generated so they can never drift again:
//   1. tokens-css.js is COPIED from the installed @ikenga/tokens (single source
//      of truth — the package's own build-css.mjs already emits it).
//   2. tasks-css.js is CODEGEN'd from dist/tasks.css via one JSON.stringify call.
//
// Both ride the script path (not <link>/@import) because WebKitGTK cannot load
// subresources from the about:srcdoc the shell mounts; app.js injects each as an
// inline <style>. Guard against drift in CI with `pnpm -r build && git diff --exit-code`.
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { vendorRuntime } from '../../../lib/pkg-runtime/vendor.mjs';

const require = createRequire(import.meta.url);
mkdirSync('dist/lib', { recursive: true });

// 1. Vendor the reconciled tokens JS-string from the installed @ikenga/tokens.
copyFileSync(require.resolve('@ikenga/tokens/tokens-css'), 'dist/lib/tokens-css.js');

// 1b. Vendor the app-kit component layer (P3 inc-3) — the kit primitives tasks
//     now consumes (.frame*, .ip-*, .dense-row*, .tk-badge, .tk-execmode). Copied
//     from the same installed @ikenga/tokens so it can never drift; app.js injects
//     it between tokens-css and tasks-css (tokens → app-kit → domain residue).
copyFileSync(require.resolve('@ikenga/tokens/app-kit-css'), 'dist/lib/app-kit-css.js');

// 2. Regenerate the domain CSS string from dist/tasks.css (the source of truth).
const css = readFileSync('dist/tasks.css', 'utf8');
const header =
  '// GENERATED by scripts/build.mjs from dist/tasks.css — do not edit.\n' +
  '// CSS-as-string: WebKitGTK cannot load link/fetch subresources from the\n' +
  '// about:srcdoc the shell mounts, so app.js injects this as an inline <style>.\n';
writeFileSync('dist/lib/tasks-css.js', header + 'export default ' + JSON.stringify(css) + '\n');

// 3. Vendor the shared no-build runtime (bridge + ui) from @ikenga/pkg-runtime —
//    single source of truth (WP-19). The generated pkg-id.js carries this pkg's
//    source-id + log tag, so the copied bridge.js stays byte-identical across pkgs.
//    `operator` brings the shared fail-safe operator-identity predicates (the
//    same copy the other no-build app pkgs vendor) for the "Me" / "You" logic.
const runtime = vendorRuntime({
  destLibDir: fileURLToPath(new URL('../dist/lib', import.meta.url)),
  pkgId: 'com.ikenga.tasks',
  logTag: 'tasks',
  files: ['bridge', 'ui', 'operator'],
});

console.log(
  '[tasks build] vendored tokens-css.js + app-kit-css.js + regenerated tasks-css.js from dist/tasks.css; runtime: ' +
    runtime.join(', '),
);
