export interface AudioAnalysis {
	bpm?: number;
	downbeats?: number[]; // timestamps in seconds
	beats?: number[];
	onsets?: number[];
	source?: string;
}

export interface ResolveMarker {
	name: string;
	color: 'Blue' | 'Yellow' | 'Green' | 'Cyan' | 'Red';
	frame: number;
	comment?: string;
}

export function generateResolveBeatMarkers(analysis: AudioAnalysis, fps: number = 24): ResolveMarker[] {
	const markers: ResolveMarker[] = [];

	if (analysis.downbeats) {
		for (const sec of analysis.downbeats) {
			const frame = Math.round(sec * fps);
			markers.push({
				name: 'Downbeat',
				color: 'Blue',
				frame,
				comment: `Downbeat at ${sec.toFixed(3)}s`,
			});
		}
	}

	if (analysis.onsets) {
		for (const sec of analysis.onsets) {
			const frame = Math.round(sec * fps);
			// Avoid duplicate markers if downbeat already set at this frame
			if (!markers.some((m) => m.frame === frame)) {
				markers.push({
					name: 'Onset',
					color: 'Yellow',
					frame,
					comment: `Transient onset at ${sec.toFixed(3)}s`,
				});
			}
		}
	}

	return markers.sort((a, b) => a.frame - b.frame);
}

export function exportResolveMarkerPythonScript(markers: ResolveMarker[], timelineName: string = 'Ikenga Timeline'): string {
	const markerCalls = markers
		.map((m) => `timeline.AddMarker(${m.frame}, "${m.color}", "${m.name}", "${m.comment || ''}", 1)`)
		.join('\n');

	return `
# DaVinci Resolve Beat Marker Injector
# Generated by Ikenga Studio Beat Detect

import DaVinciResolveScript as dvr

resolve = dvr.scriptapp("Resolve")
if resolve:
    pm = resolve.GetProjectManager()
    proj = pm.GetCurrentProject()
    if proj:
        timeline = proj.GetCurrentTimeline()
        if timeline:
            print(f"Injecting {len(markers)} markers into {timeline.GetName()}")
${markerCalls}
            print("Successfully injected beat-sync markers.")
`;
}
